version:  "v2"

services:
  user-service:
    build:  ./user-service
    ports:
      - 8082:8082
  order-service:
    build:  ./order-service
    ports:
      - 8081:8081
  gateway:
    build:  ./gateway
    ports:
      - 10010:10010