server:
  port: 8083

spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 192.168.1.101 # ip address
    port: 5672
    username: jasfair
    password: HYSBEST1234
    virtual-host: /
    listener:
      simple:
        prefetch: 1